# Generated by Django 3.1.1 on 2021-04-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rubricas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programa",
            name="apes",
            field=models.ManyToManyField(to="rubricas.APE"),
        ),
        migrations.AlterField(
            model_name="programa",
            name="competencias",
            field=models.ManyToManyField(to="rubricas.Competencia"),
        ),
    ]
