# Generated by Django 3.1.1 on 2021-06-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rubricas", "0003_auto_20210430_1407"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
