# Generated by Django 3.1.1 on 2021-06-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rubricas", "0008_auto_20210626_1730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumenapesemestre",
            name="secciones",
            field=models.ManyToManyField(blank=True, to="rubricas.Seccion"),
        ),
    ]
