# Generated by Django 3.1.1 on 2021-06-27 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubricas', '0011_seccion_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubricaseccion',
            name='secciones',
        ),
        migrations.AddField(
            model_name='rubricaseccion',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubricas.seccion'),
        ),
    ]
